# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18v0OEw2xrs5vISyS7aYS0FjdiyaiBZ4v
"""


import streamlit as st
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
import pickle

with open('model.pkl','rb') as f:
  model = pickle.load(f)

st.title("STOCK PREDICITION")
st.markdown('Enter the details below to predict the tommorow opening price of Jubliant Foodworks Limited:')
volume=st.number_input('Enter the todays Volume')
high=st.number_input('Enter the todays High')
low=st.number_input('Enter the todays Low')
o=st.number_input('Enter the todays Open')

if st.button("PREDICT"):
  data=np.array([[volume,high,low,o]])
  ans=model.predict(data)
  st.success("The predicted opening price is",ans[0])
